//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Inventory"",
            ""id"": ""c668ca6e-6227-445f-a147-613c82b9644a"",
            ""actions"": [
                {
                    ""name"": ""Show/Hide Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""9b6467f0-92b8-4e12-8d56-b79726b61acd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move Cursor"",
                    ""type"": ""Value"",
                    ""id"": ""4888d0a6-dbba-4491-b585-ee4e9f3e52f0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""c547a270-5565-4677-8caa-df6605268246"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Remove/Reset"",
                    ""type"": ""Button"",
                    ""id"": ""4b1e81bc-16a9-4f46-9208-1538744c4352"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move Cursor Up"",
                    ""type"": ""Button"",
                    ""id"": ""748e8265-d022-4a98-9b0f-f039f4e5c94a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move Cursor Down"",
                    ""type"": ""Button"",
                    ""id"": ""40436c4c-c754-4398-878a-495660c54074"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move Cursor Left"",
                    ""type"": ""Button"",
                    ""id"": ""22240dcd-9a01-4e3f-a822-c8c5b651211a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move Cursor Right"",
                    ""type"": ""Button"",
                    ""id"": ""d87c3d44-c207-4db2-9dbf-5887b6030808"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change Resolution"",
                    ""type"": ""Value"",
                    ""id"": ""1cacec64-bca5-4662-b469-89fa31721b29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cefa2b57-37f3-480a-abe0-a8bce1465fce"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Show/Hide Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""743123d5-8d92-4818-8db9-75ebf8f63033"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Show/Hide Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8580ce99-cdad-4dae-b511-b5ad77511c87"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Show/Hide Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ddc03c0-5538-4715-921d-c73a6cd98c14"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c84c58e0-2db9-4ece-a1b6-e511df8b54db"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ba8a60bf-f94f-4409-9953-82bf7aaeab3e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9b496fee-1f01-4778-8764-a05d24f894fa"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f9a6e25a-41c7-4aa4-abe3-df459eaf1556"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9a41e9a4-f879-41ad-a449-c2b6aeb41d55"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a0e9700d-e74f-4181-ae7f-2fa85cf6d2a7"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b724280f-64a8-4216-ba0e-f22d2f8e4044"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f192630a-a1b6-4e60-b144-94b89eabcdd6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4dac9c4-d861-4105-b6f7-434b57ad73af"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Remove/Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""738a0898-7400-4f27-acd5-7bd6ba71f7dd"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Remove/Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f07d503-b93d-4c87-8f4f-377d1e3b863d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6dcf2f66-e4db-497e-a075-e62062f101d5"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc2489c9-23c8-42df-8fcf-b1f11b71dbb8"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b60c3ffb-57fe-48df-86b9-8a242740114c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8256bea3-3671-4961-bd66-447e10bed7c2"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""778c4cda-1646-42ac-8ce9-7de52c9a9b09"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78bb9e2d-f6f6-4f8c-9824-1b3dfd43e5db"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c242f1e9-a8ef-4bd2-bf30-5c5d668b7a86"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc329a98-edda-44f8-9952-3721f497319a"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f156b38-42ea-4d23-8965-6cd88c6e15a1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f453cb4b-6d3a-48fe-8dd6-3b5adc0b928b"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""266863e6-ec9e-4338-8799-381c70490fdd"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""2b73620e-8aee-4631-bf7a-bbdf0e5edd5d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Resolution"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bfedbe76-fe8c-47d7-b552-a873fbb8ad79"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Resolution"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cc44f7fd-7413-493b-ba41-4f2b7ec3c90c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Resolution"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""b1ecc563-d28e-4e6c-a763-c565628ef9af"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Resolution"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b7cd8081-1ffc-47b7-9bfd-17f6b10ed554"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Resolution"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""eec288e7-4e2c-41f8-962a-5c1cbfbe3357"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Resolution"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Inventory
        m_Inventory = asset.FindActionMap("Inventory", throwIfNotFound: true);
        m_Inventory_ShowHideInventory = m_Inventory.FindAction("Show/Hide Inventory", throwIfNotFound: true);
        m_Inventory_MoveCursor = m_Inventory.FindAction("Move Cursor", throwIfNotFound: true);
        m_Inventory_Select = m_Inventory.FindAction("Select", throwIfNotFound: true);
        m_Inventory_RemoveReset = m_Inventory.FindAction("Remove/Reset", throwIfNotFound: true);
        m_Inventory_MoveCursorUp = m_Inventory.FindAction("Move Cursor Up", throwIfNotFound: true);
        m_Inventory_MoveCursorDown = m_Inventory.FindAction("Move Cursor Down", throwIfNotFound: true);
        m_Inventory_MoveCursorLeft = m_Inventory.FindAction("Move Cursor Left", throwIfNotFound: true);
        m_Inventory_MoveCursorRight = m_Inventory.FindAction("Move Cursor Right", throwIfNotFound: true);
        m_Inventory_ChangeResolution = m_Inventory.FindAction("Change Resolution", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Inventory
    private readonly InputActionMap m_Inventory;
    private IInventoryActions m_InventoryActionsCallbackInterface;
    private readonly InputAction m_Inventory_ShowHideInventory;
    private readonly InputAction m_Inventory_MoveCursor;
    private readonly InputAction m_Inventory_Select;
    private readonly InputAction m_Inventory_RemoveReset;
    private readonly InputAction m_Inventory_MoveCursorUp;
    private readonly InputAction m_Inventory_MoveCursorDown;
    private readonly InputAction m_Inventory_MoveCursorLeft;
    private readonly InputAction m_Inventory_MoveCursorRight;
    private readonly InputAction m_Inventory_ChangeResolution;
    public struct InventoryActions
    {
        private @PlayerControls m_Wrapper;
        public InventoryActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ShowHideInventory => m_Wrapper.m_Inventory_ShowHideInventory;
        public InputAction @MoveCursor => m_Wrapper.m_Inventory_MoveCursor;
        public InputAction @Select => m_Wrapper.m_Inventory_Select;
        public InputAction @RemoveReset => m_Wrapper.m_Inventory_RemoveReset;
        public InputAction @MoveCursorUp => m_Wrapper.m_Inventory_MoveCursorUp;
        public InputAction @MoveCursorDown => m_Wrapper.m_Inventory_MoveCursorDown;
        public InputAction @MoveCursorLeft => m_Wrapper.m_Inventory_MoveCursorLeft;
        public InputAction @MoveCursorRight => m_Wrapper.m_Inventory_MoveCursorRight;
        public InputAction @ChangeResolution => m_Wrapper.m_Inventory_ChangeResolution;
        public InputActionMap Get() { return m_Wrapper.m_Inventory; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InventoryActions set) { return set.Get(); }
        public void SetCallbacks(IInventoryActions instance)
        {
            if (m_Wrapper.m_InventoryActionsCallbackInterface != null)
            {
                @ShowHideInventory.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnShowHideInventory;
                @ShowHideInventory.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnShowHideInventory;
                @ShowHideInventory.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnShowHideInventory;
                @MoveCursor.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursor;
                @MoveCursor.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursor;
                @MoveCursor.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursor;
                @Select.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnSelect;
                @RemoveReset.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnRemoveReset;
                @RemoveReset.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnRemoveReset;
                @RemoveReset.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnRemoveReset;
                @MoveCursorUp.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorUp;
                @MoveCursorUp.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorUp;
                @MoveCursorUp.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorUp;
                @MoveCursorDown.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorDown;
                @MoveCursorDown.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorDown;
                @MoveCursorDown.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorDown;
                @MoveCursorLeft.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorLeft;
                @MoveCursorLeft.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorLeft;
                @MoveCursorLeft.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorLeft;
                @MoveCursorRight.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorRight;
                @MoveCursorRight.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorRight;
                @MoveCursorRight.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnMoveCursorRight;
                @ChangeResolution.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnChangeResolution;
                @ChangeResolution.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnChangeResolution;
                @ChangeResolution.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnChangeResolution;
            }
            m_Wrapper.m_InventoryActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ShowHideInventory.started += instance.OnShowHideInventory;
                @ShowHideInventory.performed += instance.OnShowHideInventory;
                @ShowHideInventory.canceled += instance.OnShowHideInventory;
                @MoveCursor.started += instance.OnMoveCursor;
                @MoveCursor.performed += instance.OnMoveCursor;
                @MoveCursor.canceled += instance.OnMoveCursor;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @RemoveReset.started += instance.OnRemoveReset;
                @RemoveReset.performed += instance.OnRemoveReset;
                @RemoveReset.canceled += instance.OnRemoveReset;
                @MoveCursorUp.started += instance.OnMoveCursorUp;
                @MoveCursorUp.performed += instance.OnMoveCursorUp;
                @MoveCursorUp.canceled += instance.OnMoveCursorUp;
                @MoveCursorDown.started += instance.OnMoveCursorDown;
                @MoveCursorDown.performed += instance.OnMoveCursorDown;
                @MoveCursorDown.canceled += instance.OnMoveCursorDown;
                @MoveCursorLeft.started += instance.OnMoveCursorLeft;
                @MoveCursorLeft.performed += instance.OnMoveCursorLeft;
                @MoveCursorLeft.canceled += instance.OnMoveCursorLeft;
                @MoveCursorRight.started += instance.OnMoveCursorRight;
                @MoveCursorRight.performed += instance.OnMoveCursorRight;
                @MoveCursorRight.canceled += instance.OnMoveCursorRight;
                @ChangeResolution.started += instance.OnChangeResolution;
                @ChangeResolution.performed += instance.OnChangeResolution;
                @ChangeResolution.canceled += instance.OnChangeResolution;
            }
        }
    }
    public InventoryActions @Inventory => new InventoryActions(this);
    public interface IInventoryActions
    {
        void OnShowHideInventory(InputAction.CallbackContext context);
        void OnMoveCursor(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnRemoveReset(InputAction.CallbackContext context);
        void OnMoveCursorUp(InputAction.CallbackContext context);
        void OnMoveCursorDown(InputAction.CallbackContext context);
        void OnMoveCursorLeft(InputAction.CallbackContext context);
        void OnMoveCursorRight(InputAction.CallbackContext context);
        void OnChangeResolution(InputAction.CallbackContext context);
    }
}
